name: Check PR Status
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  prStatus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get PR Status
        id: PR
        run: |
          number=$(echo "${{ github.event.pull_request.url }}" | awk -F/ '{print $NF}')
          status=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/$number" \
                        | jq -r '.state')
          echo current PR $pr_number status: $status
          echo "::set-output name=state::$status"

      - name: Perform Actions Based on PR Status
        run: |
          echo "PR status: ${{ steps.PR.outputs.status }}"

      - name: Evaluate if branches are merged
        if: steps.PR.outputs.state != 'closed'
        run: |
          exit 402
